// <auto-generated />
using System;
using System.Text.Json.Nodes;
using GameDocumentEngine.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameDocumentEngine.Server.Migrations
{
    [DbContext(typeof(DocumentDbContext))]
    [Migration("20231121135956_VersionAndOptions")]
    partial class VersionAndOptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameDocumentEngine.Server.Documents.DocumentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("GameId", "Id");

                    b.HasIndex("GameId", "FolderId", "Name");

                    b.HasIndex("GameId", "Type", "Name");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("GameDocumentEngine.Server.Documents.DocumentUserModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Options")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("GameId", "DocumentId");

                    b.HasIndex("UserId", "GameId");

                    b.ToTable("DocumentUsers");
                });

            modelBuilder.Entity("GameDocumentEngine.Server.Documents.GameModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GameDocumentEngine.Server.Documents.GameUserModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameOverride")
                        .HasColumnType("text");

                    b.Property<string>("Options")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("GameUsers");
                });

            modelBuilder.Entity("GameDocumentEngine.Server.Security.GameInviteModel", b =>
                {
                    b.Property<string>("InviteId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Expiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("GameRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsesRemaining")
                        .HasColumnType("integer");

                    b.HasKey("InviteId");

                    b.HasIndex("Expiration");

                    b.HasIndex("GameId", "Expiration");

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("GameDocumentEngine.Server.Users.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleNameId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Options")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.HasKey("Id");

                    b.HasIndex("GoogleNameId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GameDocumentEngine.Server.Documents.DocumentModel", b =>
                {
                    b.HasOne("GameDocumentEngine.Server.Documents.DocumentModel", "Folder")
                        .WithMany("FolderContents")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GameDocumentEngine.Server.Documents.GameModel", "Game")
                        .WithMany("Documents")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameDocumentEngine.Server.Documents.DocumentUserModel", b =>
                {
                    b.HasOne("GameDocumentEngine.Server.Users.UserModel", "User")
                        .WithMany("Documents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GameDocumentEngine.Server.Documents.DocumentModel", "Document")
                        .WithMany("Players")
                        .HasForeignKey("GameId", "DocumentId")
                        .HasPrincipalKey("GameId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GameDocumentEngine.Server.Documents.GameUserModel", "GameUser")
                        .WithMany("Documents")
                        .HasForeignKey("UserId", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("GameUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameDocumentEngine.Server.Documents.GameUserModel", b =>
                {
                    b.HasOne("GameDocumentEngine.Server.Documents.GameModel", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDocumentEngine.Server.Users.UserModel", "User")
                        .WithMany("Games")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameDocumentEngine.Server.Security.GameInviteModel", b =>
                {
                    b.HasOne("GameDocumentEngine.Server.Documents.GameModel", "Game")
                        .WithMany("ActiveInvites")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameDocumentEngine.Server.Documents.DocumentModel", b =>
                {
                    b.Navigation("FolderContents");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("GameDocumentEngine.Server.Documents.GameModel", b =>
                {
                    b.Navigation("ActiveInvites");

                    b.Navigation("Documents");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("GameDocumentEngine.Server.Documents.GameUserModel", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("GameDocumentEngine.Server.Users.UserModel", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
