apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: docs-engine-monitor
  namespace: game-docs-engine
spec:
  strategy: allInOne
  storage:
    type: memory
    options:
      memory:
        max-traces: 100000
  ingress:
    enabled: false
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-query
  namespace: game-docs-engine
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: jaeger.vtt.dekrey.net
    http:
      paths:
      - backend:
          service:
            name: docs-engine-monitor-query
            port:
              number: 16686
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - jaeger.vtt.dekrey.net
    secretName: jaeger-tls