openapi: 3.0.1
info:
  title: GameDocumentEngine
  version: v1
paths:
  /user:
    get:
      operationId: getCurrentUser
      security:
        - AuthenticatedUser: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CurrentUserDetails"
    patch:
      operationId: patchUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              format: patch
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDetails"
        400:
          description: There was a problem applying the patch
          content:
            application/json:
              schema:
                type: string
        409:
          description: User was updated while request was being processed; try again later.
  /login:
    summary: Logs the user in
    get:
      operationId: login
      summary: Logs the user in
      parameters:
        - in: query
          name: returnUrl
          schema:
            type: string
            pattern: "^/[^/].*"
          required: false
      responses:
        302:
          description: Redirects to login url
  /game-type:
    get:
      operationId: listGameTypes
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GameTypeSummary"
  /game:
    get:
      operationId: listGames
      parameters:
        - name: page
          schema: { type: integer }
          required: true
          in: query
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedGameList"
    post:
      operationId: createGame
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateGameDetails"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameDetailsWithId"
  /game/{gameId}:
    get:
      x-dotnet-mvc-server-controller: Game
      operationId: getGameDetails
      parameters:
      - name: gameId
        in: path
        required: true
        schema: { type: string }
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameDetails"
    delete:
      x-dotnet-mvc-server-controller: Game
      operationId: deleteGame
      parameters:
      - name: gameId
        in: path
        required: true
        schema: { type: string }
      responses:
        200:
          description: Success
    patch:
      x-dotnet-mvc-server-controller: Game
      operationId: patchGame
      parameters:
      - name: gameId
        in: path
        required: true
        schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              format: patch
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameDetails"
        400:
          description: There was a problem applying the patch
          content:
            application/json:
              schema:
                type: string
        404:
          description: Target game not found
        409:
          description: Game was updated while request was being processed; try again later.
  /game/{gameId}/document/{typeId}/{id}:
    get:
      x-dotnet-mvc-server-controller: Document
      operationId: getDocument
      parameters:
      - name: gameId
        in: path
        required: true
        schema: { type: string }
      - name: typeId
        in: path
        required: true
        schema: { type: string }
      - name: id
        in: path
        required: true
        schema: { type: string }
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                format: any
        404:
          description: Not Found
    put:
      x-dotnet-mvc-server-controller: Document
      operationId: putDocument
      parameters:
      - name: gameId
        in: path
        required: true
        schema: { type: string }
      - name: typeId
        in: path
        required: true
        schema: { type: string }
      - name: id
        in: path
        required: true
        schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              format: any
      responses:
        200:
          description: Success
        400:
          description: Could not parse request
          content:
            application/json:
              schema:
                type: string
    patch:
      x-dotnet-mvc-server-controller: Document
      operationId: patchDocument
      parameters:
      - name: gameId
        in: path
        required: true
        schema: { type: string }
      - name: typeId
        in: path
        required: true
        schema: { type: string }
      - name: id
        in: path
        required: true
        schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              format: patch
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                format: any
        400:
          description: There was a problem applying the patch
          content:
            application/json:
              schema:
                type: string
        404:
          description: Target document not found
        409:
          description: Document was updated while request was being processed; try again later.
components:
  securitySchemes:
    AuthenticatedUser:
      type: apiKey
      in: cookie
      name: .AspNetCore.Cookies

  schemas:
    Paginated:
      type: object
      required:
        - totalPageCount
      properties:
        totalPageCount: { type: integer }
    PaginatedGameList:
      allOf:
      - $ref: '#/components/schemas/Paginated'
      - type: object
        required:
        - items
        properties:
          items:
            type: array
            items:
              $ref: '#/components/schemas/GameSummary'

    CreateGameDetails:
      type: object
      required:
      - name
      - type
      properties:
        name: { type: string }
        type: { type: string }
    EditableGameDetails:
      type: object
      required:
      - name
      properties:
        name: { type: string }
    GameDetails:
      allOf:
        - $ref: '#/components/schemas/EditableGameDetails'
        - type: object
          required:
          - lastUpdated
          - players
          - inviteUrl
          properties:
            lastUpdated: { type: string, format: date-time }
            players:
              type: array
              items:
                type: string
            inviteUrl: { type: string }
    GameDetailsWithId:
      allOf:
        - $ref: '#/components/schemas/GameDetails'
        - type: object
          required:
            - id
          properties:
            id: { type: string }
    GameSummary:
      type: object
      required:
        - id
      properties:
        id: { type: string }
        name: { type: string }
    CurrentUserDetails:
      allOf:
      - $ref: '#/components/schemas/UserDetails'
      - type: object
        required:
          - isFirstTime
        properties:
          # TODO: There should be a better way
          isFirstTime: { type: boolean }
    UserDetails:
      type: object
      required:
        - name
      properties:
        name: { type: string }

    GameTypeSummary:
      type: object
      required:
        - name
        - description
        - objectTypes
      properties:
        name: { type: string }
        description: { type: string }
        objectTypes: { type: array, items: { type: string } }
  responses:
    "401":
      description: User was not authenticated