name: Run Tests
on:
  workflow_dispatch: {}
  # pull_request:
  #   types: [edited, opened, reopened, synchronize, ready_for_review]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: ./.github/workflows/parts/cache/
    - name: 'Run tests'
      run: |
        dotnet test
